[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["node_modules/@img/**/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
